<?php

/**
 * Implements hook_block_info()
 */ 
function audience_form_block_info() {
   $blocks['audience_form'] = array(
    'info' => t('Custom Audience Form'),
   'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_view()
 */ 
function audience_form_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'audience_form':
      $block['subject'] = t("I'm a ...");
      $block['content'] =  drupal_get_form('_build_audience_form');
    break;
  }
  return $block;
}

/**
*  Create a new form
*/
function _build_audience_form($form, $form_state) {

  $form['#attached']['js'] = array(
    drupal_get_path('module', 'audience_form') . '/audience_form.js',
  );
  
  $form ['askHeader'] = array(
    '#class' => 'region region-navigation',
    '#prefix' => '<div id="askHeader">',
    '#suffix' => '</div>',
  );
  
  $form ['askHeader']['ask'] = array(
    '#prefix' => '<div id="ask"><a href=""><span  data-icon="&#xe00b;" aria-hidden="true"></span>  Ask a Librarian</a><!--<hr>-->',
    '#suffix' => '</div>',
  );
  
  $form ['askHeader']['audtopic'] = array(
    '#prefix' => '<div id="audtopic">',
    '#suffix' => '</div>',
  );
  
  $form ['askHeader']['audtopic']['aud'] = array(
    '#prefix' => "<div id='aud'><div id='aud-title'>I'm a...</div>",
    '#title' => t("I'm a..."),
    '#suffix' => '</div>',
  );
  
  $form ['askHeader']['audtopic']['topic'] = array(
    '#prefix' => "<div id='topic'><div id='topic-title'>My subject is...</div>",
    '#title' => t("My subject is..."),
    '#suffix' => '</div>',
  );

  $form['askHeader']['audtopic']['aud']['audience'] = array(
    '#prefix' => '<div id="audience-div">',
    '#suffix' => '</div>',
    '#type' => 'select',
    '#id' => 'audience-select',
    '#options' => array(
      ''=>'-Select One-',
      '/ima/undergraduate' => t('Undergraduate'),
      '/ima/grad-student' => t('Graduate'),
      '/ima/engineering-student' => t('Engineering Student'),
      '/ima/faculty-member' => t('Faculty Member'),
      '/ima/tufts-staff-member' => t('Tufts Staff Member'),
      '/ima/alumni' => t('Alumni'),
      '/ima/visitor' => t('Visitor'),
      '/ima/person-with-a-disability' => t('Person with a Disability'),
      '/ima/another-type-of-library-patron' => t('Other Type of User'),
    ),
    '#default_value'=>'',

  );
  $form['askHeader']['audtopic']['topic']['subjects'] = array(
    '#type' => 'select',
    '#id' => 'subject-select',
    '#options' => array(
      ''=>'-Select One-',
      '/subject-resources/arts&humanities' => t('Arts & Humanities'),
      '/subject-resources/engineering' => t('Engineering'),
      '/subject-resources/social-sciences' => t('Social Sciences'),
      '/subject-resources/science' => t('Science'),
      '/subject-resources/see-all-subjects' => t('See All Subjects'),
    ),
    '#default_value'=>'',
    '#prefix' => '<div id="topic-div">',
    '#suffix' => '</div>',
  );
  return $form;
}






